import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'app.title': 'OPPO',
    'nav.dashboard': 'Дашборд',
    'nav.analytics': 'Аналитика',
    'nav.sales': 'Продажи',
    'nav.stock': 'Остатки',
    'nav.training': 'Обучение',
    'nav.tasks': 'Задачи',
    'nav.products': 'Продукты',
    'nav.bonus': 'Бонусы',
    'nav.motivations': 'Мотивации',
    'nav.focus': 'Фокусы',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    'nav.users': 'Пользователи',
    'nav.orgStructure': 'Оргструктура',
    'nav.kefSchemes': 'KEF схемы',
    'nav.retailPrices': 'Розничные цены',
    'nav.inventories': 'Запасы',
    'nav.chat': 'Чат',
    'role.promoter': 'Промоутер',
    'role.supervisor': 'Супервайзер',
    'role.office': 'Офис',
    'role.admin': 'Админ',
    'role.trainer': 'Тренер',
    'filters.period': 'Период',
    'filters.network': 'Сеть',
    'filters.store': 'Магазин',
    'filters.product': 'Модель',
    'filters.variant': 'Память',
    'kpi.bonus': 'Мой бонус',
    'kpi.salesQty': 'Продажи (шт)',
    'kpi.salesAmt': 'Сумма продаж',
    'kpi.plan': 'План',
    'kpi.progress': 'Прогресс',
    'kpi.projection': 'Проекция',
    'stock.update': 'Обновить остатки',
    'stock.confirmNoChanges': 'Подтвердить без изменений',
    'sync.offline': 'Синхронизация офлайн',
    'actions.save': 'Сохранить',
    'actions.edit': 'Редактировать',
    'actions.delete': 'Удалить',
    'actions.add': 'Добавить',
    'actions.cancel': 'Отмена',
    'actions.back': 'Назад',
    'actions.logout': 'Выход',
    'confirm.delete': 'Подтвердите удаление',
    'reminder.stocksNeeded': 'Требуется обновить остатки',
    'theme.light': 'Светлая',
    'theme.dark': 'Тёмная',
    'theme.system': 'Системная',
    'currency': '₸',
    'dashboard.title': 'OPPO Dashboard',
    'dashboard.roleUndefined': 'Роль не определена',
    'dashboard.mySales': 'Мои продажи',
    'dashboard.sync': 'Синхронизировать',
    'dashboard.today': 'Сегодня',
    'dashboard.week': 'За неделю',
    'dashboard.month': 'За месяц',
    'dashboard.revenue': 'Выручка',
    'dashboard.quantity': 'Количество',
    'dashboard.bonuses': 'Бонусы',
    'dashboard.avgCheck': 'Средний чек',
    'dashboard.activeMotivations': 'Активные мотивации',
    'dashboard.syncComplete': 'Синхронизация завершена',
    'dashboard.dataUpdated': 'Данные успешно обновлены',
    'dashboard.syncError': 'Ошибка синхронизации',
    'dashboard.syncFailed': 'Не удалось синхронизировать данные',
    'dashboard.loadError': 'Не удалось загрузить статистику',
    'dashboard.filters': 'Фильтры',
    'dashboard.thisWeek': 'Эта неделя',
    'dashboard.lastWeek': 'Прошлая неделя',
    'dashboard.thisMonth': 'Этот месяц',
    'dashboard.lastMonth': 'Прошлый месяц',
    'dashboard.wow': 'Неделя к неделе (WoW)',
    'dashboard.mom': 'Месяц к месяцу (MoM)',
    'dashboard.dailyRevenue': 'Выручка по дням',
    'dashboard.topModels': 'Топ-5 моделей',
    'dashboard.lowInventory': 'Низкие остатки',
    'dashboard.allRegions': 'Все регионы',
    'dashboard.allNetworks': 'Все сети',
    'dashboard.region': 'Регион',
    'dashboard.network': 'Сеть',
    'dashboard.byRegions': 'По регионам',
    'dashboard.byNetworks': 'По сетям',
    'dashboard.alerts': 'Сигналы',
    'dashboard.pcs': 'шт',
    'dashboard.selectRegion': 'Выберите регион',
    'error.title': 'Ошибка',
    'error.loadFailed': 'Не удалось загрузить данные',
    'trainer.promoters': 'Промоутеры',
    'trainer.tests': 'Тесты',
    'trainer.materials': 'Материалы',
    'trainer.promotersList': 'Список промоутеров',
    'trainer.activeTests': 'Активные тесты',
    'profile.title': 'Личный кабинет',
    'profile.personalInfo': 'Личная информация',
    'profile.fullName': 'ФИО',
    'profile.patronymic': 'Отчество',
    'profile.phone': 'Телефон',
    'profile.city': 'Город',
    'profile.email': 'Email',
    'profile.role': 'Роль',
    'profile.accountInfo': 'Информация об аккаунте',
    'profile.updated': 'Обновлено',
    'profile.updateSuccess': 'Профиль успешно обновлен',
    'common.noPhone': 'Нет телефона',
    'common.save': 'Сохранить',
    'common.saving': 'Сохранение...',
  },
  en: {
    'app.title': 'OPPO',
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Analytics',
    'nav.sales': 'Sales',
    'nav.stock': 'Stock',
    'nav.training': 'Training',
    'nav.tasks': 'Tasks',
    'nav.products': 'Products',
    'nav.bonus': 'Bonuses',
    'nav.motivations': 'Motivations',
    'nav.focus': 'Focus',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.users': 'Users',
    'nav.orgStructure': 'Org Structure',
    'nav.kefSchemes': 'KEF Schemes',
    'nav.retailPrices': 'Retail Prices',
    'nav.inventories': 'Inventories',
    'nav.chat': 'Chat',
    'role.promoter': 'Promoter',
    'role.supervisor': 'Supervisor',
    'role.office': 'Office',
    'role.admin': 'Admin',
    'role.trainer': 'Trainer',
    'filters.period': 'Period',
    'filters.network': 'Network',
    'filters.store': 'Store',
    'filters.product': 'Model',
    'filters.variant': 'Memory',
    'kpi.bonus': 'My Bonus',
    'kpi.salesQty': 'Sales (pcs)',
    'kpi.salesAmt': 'Sales Amount',
    'kpi.plan': 'Plan',
    'kpi.progress': 'Progress',
    'kpi.projection': 'Projection',
    'stock.update': 'Update Stock',
    'stock.confirmNoChanges': 'Confirm Without Changes',
    'sync.offline': 'Offline Sync',
    'actions.save': 'Save',
    'actions.edit': 'Edit',
    'actions.delete': 'Delete',
    'actions.add': 'Add',
    'actions.cancel': 'Cancel',
    'actions.back': 'Back',
    'actions.logout': 'Logout',
    'confirm.delete': 'Confirm Deletion',
    'reminder.stocksNeeded': 'Stock update required',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'currency': '₸',
    'dashboard.title': 'OPPO Dashboard',
    'dashboard.roleUndefined': 'Role undefined',
    'dashboard.mySales': 'My Sales',
    'dashboard.sync': 'Sync',
    'dashboard.today': 'Today',
    'dashboard.week': 'This Week',
    'dashboard.month': 'This Month',
    'dashboard.revenue': 'Revenue',
    'dashboard.quantity': 'Quantity',
    'dashboard.bonuses': 'Bonuses',
    'dashboard.avgCheck': 'Avg Check',
    'dashboard.activeMotivations': 'Active Motivations',
    'dashboard.syncComplete': 'Sync Complete',
    'dashboard.dataUpdated': 'Data updated successfully',
    'dashboard.syncError': 'Sync Error',
    'dashboard.syncFailed': 'Failed to sync data',
    'dashboard.loadError': 'Failed to load statistics',
    'dashboard.filters': 'Filters',
    'dashboard.thisWeek': 'This Week',
    'dashboard.lastWeek': 'Last Week',
    'dashboard.thisMonth': 'This Month',
    'dashboard.lastMonth': 'Last Month',
    'dashboard.wow': 'Week over Week (WoW)',
    'dashboard.mom': 'Month over Month (MoM)',
    'dashboard.dailyRevenue': 'Daily Revenue',
    'dashboard.topModels': 'Top 5 Models',
    'dashboard.lowInventory': 'Low Inventory',
    'dashboard.allRegions': 'All Regions',
    'dashboard.allNetworks': 'All Networks',
    'dashboard.region': 'Region',
    'dashboard.network': 'Network',
    'dashboard.byRegions': 'By Regions',
    'dashboard.byNetworks': 'By Networks',
    'dashboard.alerts': 'Alerts',
    'dashboard.pcs': 'pcs',
    'dashboard.selectRegion': 'Select Region',
    'error.title': 'Error',
    'error.loadFailed': 'Failed to load data',
    'trainer.promoters': 'Promoters',
    'trainer.tests': 'Tests',
    'trainer.materials': 'Materials',
    'trainer.promotersList': 'Promoters List',
    'trainer.activeTests': 'Active Tests',
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.patronymic': 'Patronymic',
    'profile.phone': 'Phone',
    'profile.city': 'City',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.accountInfo': 'Account Information',
    'profile.updated': 'Updated',
    'profile.updateSuccess': 'Profile updated successfully',
    'common.noPhone': 'No phone',
    'common.save': 'Save',
    'common.saving': 'Saving...',
  },
  kk: {
    'app.title': 'OPPO',
    'nav.dashboard': 'Бас бет',
    'nav.analytics': 'Талдау',
    'nav.sales': 'Сату',
    'nav.stock': 'Қорлар',
    'nav.training': 'Оқыту',
    'nav.tasks': 'Тапсырмалар',
    'nav.products': 'Өнімдер',
    'nav.bonus': 'Бонустар',
    'nav.motivations': 'Мотивациялар',
    'nav.focus': 'Фокустар',
    'nav.settings': 'Баптаулар',
    'nav.profile': 'Профиль',
    'nav.users': 'Пайдаланушылар',
    'nav.orgStructure': 'Ұйым құрылымы',
    'nav.kefSchemes': 'KEF схемалары',
    'nav.retailPrices': 'Бөлшек бағалар',
    'nav.inventories': 'Қорлар',
    'nav.chat': 'Чат',
    'role.promoter': 'Промоутер',
    'role.supervisor': 'Супервайзер',
    'role.office': 'Офис',
    'role.admin': 'Әкімші',
    'role.trainer': 'Тренер',
    'filters.period': 'Кезең',
    'filters.network': 'Желі',
    'filters.store': 'Дүкен',
    'filters.product': 'Модель',
    'filters.variant': 'Жад',
    'kpi.bonus': 'Менің бонусым',
    'kpi.salesQty': 'Сату (дана)',
    'kpi.salesAmt': 'Сату сомасы',
    'kpi.plan': 'Жоспар',
    'kpi.progress': 'Үдеріс',
    'kpi.projection': 'Болжам',
    'stock.update': 'Қорларды жаңарту',
    'stock.confirmNoChanges': 'Өзгертусіз растау',
    'sync.offline': 'Офлайн синхрондау',
    'actions.save': 'Сақтау',
    'actions.edit': 'Өңдеу',
    'actions.delete': 'Жою',
    'actions.add': 'Қосу',
    'actions.cancel': 'Болдырмау',
    'actions.back': 'Артқа',
    'actions.logout': 'Шығу',
    'confirm.delete': 'Жоюды растаңыз',
    'reminder.stocksNeeded': 'Қорларды жаңарту қажет',
    'theme.light': 'Жарық',
    'theme.dark': 'Қараңғы',
    'theme.system': 'Жүйелік',
    'currency': '₸',
    'dashboard.title': 'OPPO Бас бет',
    'dashboard.roleUndefined': 'Рөл анықталмаған',
    'dashboard.mySales': 'Менің сатуларым',
    'dashboard.sync': 'Синхрондау',
    'dashboard.today': 'Бүгін',
    'dashboard.week': 'Апта ішінде',
    'dashboard.month': 'Ай ішінде',
    'dashboard.revenue': 'Түсім',
    'dashboard.quantity': 'Саны',
    'dashboard.bonuses': 'Бонустар',
    'dashboard.avgCheck': 'Орташа чек',
    'dashboard.activeMotivations': 'Белсенді мотивациялар',
    'dashboard.syncComplete': 'Синхрондау аяқталды',
    'dashboard.dataUpdated': 'Деректер сәтті жаңартылды',
    'dashboard.syncError': 'Синхрондау қатесі',
    'dashboard.syncFailed': 'Деректерді синхрондау сәтсіз болды',
    'dashboard.loadError': 'Статистиканы жүктеу сәтсіз болды',
    'dashboard.filters': 'Сүзгілер',
    'dashboard.thisWeek': 'Осы апта',
    'dashboard.lastWeek': 'Өткен апта',
    'dashboard.thisMonth': 'Осы ай',
    'dashboard.lastMonth': 'Өткен ай',
    'dashboard.wow': 'Апта бойынша (WoW)',
    'dashboard.mom': 'Ай бойынша (MoM)',
    'dashboard.dailyRevenue': 'Күндік түсім',
    'dashboard.topModels': 'Топ-5 модельдер',
    'dashboard.lowInventory': 'Төмен қорлар',
    'dashboard.allRegions': 'Барлық аймақтар',
    'dashboard.allNetworks': 'Барлық желілер',
    'dashboard.region': 'Аймақ',
    'dashboard.network': 'Желі',
    'dashboard.byRegions': 'Аймақтар бойынша',
    'dashboard.byNetworks': 'Желілер бойынша',
    'dashboard.alerts': 'Ескертулер',
    'dashboard.pcs': 'дана',
    'dashboard.selectRegion': 'Аймақты таңдаңыз',
    'error.title': 'Қате',
    'error.loadFailed': 'Деректерді жүктеу сәтсіз болды',
    'trainer.promoters': 'Промоутерлер',
    'trainer.tests': 'Тесттер',
    'trainer.materials': 'Материалдар',
    'trainer.promotersList': 'Промоутерлер тізімі',
    'trainer.activeTests': 'Белсенді тесттер',
    'profile.title': 'Жеке кабинет',
    'profile.personalInfo': 'Жеке ақпарат',
    'profile.fullName': 'Толық аты-жөні',
    'profile.patronymic': 'Әкесінің аты',
    'profile.phone': 'Телефон',
    'profile.city': 'Қала',
    'profile.email': 'Email',
    'profile.role': 'Рөл',
    'profile.accountInfo': 'Аккаунт туралы ақпарат',
    'profile.updated': 'Жаңартылды',
    'profile.updateSuccess': 'Профиль сәтті жаңартылды',
    'common.noPhone': 'Телефон жоқ',
    'common.save': 'Сақтау',
    'common.saving': 'Сақтау...',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('oppo-language');
    if (saved && ['ru', 'en', 'kk'].includes(saved)) {
      return saved as Language;
    }
    // Auto-detect from browser
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('kk')) return 'kk';
    if (browserLang.startsWith('en')) return 'en';
    return 'ru'; // Default
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('oppo-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};